version: "3.8"

services:
  proxy-server:
    image: jc21/nginx-proxy-manager
    container_name: proxy-server
    hostname: proxy-server
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    restart: unless-stopped
